# Generated by Django 5.2.7 on 2025-10-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_book_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
