# Generated by Django 5.2.7 on 2025-10-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_author_category_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
