# Generated by Django 5.2.7 on 2025-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='pages.category'),
        ),
    ]
