# Generated by Django 5.2.7 on 2025-10-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_book_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
